project: 
  type: website
  
website: 
  page-navigation: true
  title: "Python for Scientific Computing and Data Visualization" 
  site-url: "https://randomspace.github.io" 
  repo-url: https://github.com/dindagustiayu/randomspaces.github.io 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Randomspaces, 2026"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://randomspaces.github.io
        text: "randomspaces.github.io"
      - icon: github
        href: https://github.com/dindagustiayu/randomspaces.github.io
        text: "Random Spaces"
      - icon: linked in
        href: https://linkedin.com/in/dindagustiayu
        text: "Dinda Gusti Ayu"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - explore.qmd
      - section: quarto-workflows/index.qmd
        contents: 
          - section: Data Science
            contents:
              - quarto-workflows/data-science/Gaussian.md
              - quarto-workflows/data-science/the-fourier-series.md
              - quarto-workflows/data-science/linear-algebra.md
              - quarto-workflows/data-science/numpy-and-matplot.md
              - quarto-workflows/data-science/basicnumpy.md
          - section: Quantum Mechanics
            contents:
              - quarto-workflows/quantum-mechanics/particles-2d.md
          - section: Thermodynamics
            contents:
              - quarto-workflows/thermodynamics/adiabatic-process.md
      - learning-more.qmd
       
       
format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    fig-align: center


filters:
  - include-files.lua
  - quarto

  
