---
title: Learning more
---

## Inspiration

The repositories here was inpired by [Christian Hill](https://www.linkedin.com/in/christian-hill-8066b359/), the author of the book __"Learning Scientific Programming with Python (2nd edition)"__, published by University of Cambridge. The course "book" contains completed topics from general programming concepts like loops and functions, through `NumPy`, `SciPy`, and `Matplotlib` for numerical programming and data visualizations. All topics available for free from [scipython](https://scipython.com/books/book2/).

## Linked Resources

Here is a list of resources that we are linking to that have been developed by others.

- [Computational Chemistry](https://pythoninchemistry.org/ch40208/introduction/about_this_book.html) by Benjamin Morgan and Andrew McCluskey from University of Bath.
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake T VanderPlas from Google Research.
- [Drug Discovery with Python](https://github.com/alex-aziz/Drug-Discovery-with-Python) by Zhaohui Jiang and Alex Aziz from Manchester Metropolitan Unversity.


